apiVersion: v1
kind: Service
metadata:
  labels:
    name: ipmi-exporter
  name: ipmi-exporter
  namespace: monitoring
spec:
  ports:
  - name: ipmi-exporter
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ipmi-exporter
  sessionAffinity: None
  type: ClusterIP
