apiVersion: v1
data:
  app.conf: |-
    server {
        listen 80;
        charset utf-8;
        access_log off;

        location / {
            proxy_pass http://web:8000;
            proxy_set_header Host $host:$server_port;
            proxy_set_header X-Forwarded-Host $server_name;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: 2018-02-08T03:28:59Z
  name: nginx-configmap
  namespace: monitoring
  resourceVersion: "295843"
  selfLink: /api/v1/namespaces/monitoring/configmaps/nginx-configmap
  uid: 337cf88d-0c80-11e8-baca-000d3a735c76
